# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewTest', '0003_auto_20170609_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
