# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewTest', '0004_auto_20170609_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='signup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
