# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewTest', '0005_clientaccount_signup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
